name: Pelican site CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: "Set up Python 3.7"
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pelican pyyaml beautifulsoup4 ghp-import
        git clone --depth=1 --single-branch --branch mechmotum https://github.com/mechmotum/pelican-alchemy.git
        git clone --depth=1 https://github.com/getpelican/pelican-plugins.git
    - name: Build the website
      run: |
        pelican -D -v --fatal errors -s publishconf.py -o output
        git fetch origin --tags
        git checkout 2022Q3Q4
        sed -i 's|me41055|me41055/2022|' publishconf.py
        pelican -D -v --fatal errors -s publishconf.py -o output/2022
        ls output/
    - name: Deploy the website
      if: ${{ github.event_name == 'push' }}
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email mechmotum@users.noreply.github.com
        git remote add deploy "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/moorepants/me41055.git"
        ghp-import -r deploy -b gh-pages -m "Updated via Github Actions" -p output
